//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dogovor
    {
        public int DID { get; set; }
        public System.DateTime Date_of { get; set; }
        public System.DateTime Date_sd { get; set; }
        public System.DateTime Date_ok { get; set; }
        public decimal Sum { get; set; }
        public Nullable<int> CFK { get; set; }
        public Nullable<int> SFK { get; set; }
        public Nullable<int> LFK { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Ship Ship { get; set; }
        public virtual Sotrudnik Sotrudnik { get; set; }
    }
}
