//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ship
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ship()
        {
            this.Dogovor = new HashSet<Dogovor>();
        }
    
        public int LID { get; set; }
        public string Name { get; set; }
        public string Manufacture { get; set; }
        public int Power_dv { get; set; }
        public float Dlina { get; set; }
        public float Shirina { get; set; }
        public float Osadka { get; set; }
        public float Visota_bort { get; set; }
        public int Speed_max { get; set; }
        public float Vodoizmesch { get; set; }
        public float Rashod_topl { get; set; }
        public string Sostoyanie { get; set; }
        public decimal Sum_day { get; set; }
        public int LTFK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dogovor> Dogovor { get; set; }
        public virtual Tip_ship Tip_ship { get; set; }
    }
}
